# Generated by Django 5.2.8 on 2025-11-16 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2)),
                ("humidity_min", models.FloatField()),
                ("humidity_max", models.FloatField()),
                (
                    "humidity_sensor_pin",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("servo_pin", models.CharField(blank=True, max_length=20, null=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_servo_state",
                    models.CharField(
                        choices=[("ON", "Encendido"), ("OFF", "Apagado")],
                        default="OFF",
                        max_length=3,
                    ),
                ),
                ("last_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humidity", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="arduino.sensorzone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IrrigationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ON", "Encendido"), ("OFF", "Apagado")], max_length=3
                    ),
                ),
                ("humidity_at_event", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_events",
                        to="arduino.sensorzone",
                    ),
                ),
            ],
        ),
    ]
