# Generated by Django 5.2.8 on 2025-11-24 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flowerpot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_irrigation",
                    models.BooleanField(
                        default=False,
                        help_text="Si está activo, el riego se mantiene siempre encendido.",
                        verbose_name="Riego manual",
                    ),
                ),
                (
                    "automatic_irrigation",
                    models.BooleanField(
                        default=True,
                        help_text="Si está activo, el riego se decide según la humedad.",
                        verbose_name="Riego automático",
                    ),
                ),
                (
                    "last_servo_state",
                    models.CharField(
                        choices=[("ON", "Encendido"), ("OFF", "Apagado")],
                        default="OFF",
                        help_text="Último estado decidido para el servomotor.",
                        max_length=3,
                    ),
                ),
                (
                    "last_updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última actualización"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre común de la planta.",
                        max_length=255,
                        verbose_name="Nombre de la planta",
                    ),
                ),
                (
                    "humidity_min",
                    models.FloatField(
                        default=20.0,
                        help_text="Humedad mínima (%) antes de activar el riego.",
                        verbose_name="Humedad mínima (%)",
                    ),
                ),
                (
                    "humidity_max",
                    models.FloatField(
                        default=60.0,
                        help_text="Humedad máxima (%) a partir de la cual se apaga el riego.",
                        verbose_name="Humedad máxima (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IrrigationEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("ON", "Encendido"), ("OFF", "Apagado")],
                        max_length=3,
                        verbose_name="Acción",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("AUTO", "Automático")],
                        help_text="Indica si el riego fue manual o automático.",
                        max_length=7,
                        verbose_name="Modo de riego",
                    ),
                ),
                (
                    "humidity_at_event",
                    models.FloatField(
                        help_text="Humedad (%) al momento del evento de riego.",
                        verbose_name="Humedad (%) al evento",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "flowerpot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="irrigation_events",
                        to="arduino.flowerpot",
                        verbose_name="Macetero",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="flowerpot",
            name="plant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flowerpots",
                to="arduino.plants",
                verbose_name="Planta asociada",
            ),
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        help_text="Humedad medida por el sensor (%).",
                        verbose_name="Humedad (%)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de lectura"
                    ),
                ),
                (
                    "flowerpot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_readings",
                        to="arduino.flowerpot",
                        verbose_name="Macetero",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
