# Generated by Django 5.2.8 on 2025-11-24 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la categoría (por ejemplo: interior, suculenta).', max_length=100, unique=True, verbose_name='Nombre de la categoría')),
            ],
        ),
        migrations.AddField(
            model_name='plants',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL pública de la imagen de la planta.', null=True, verbose_name='URL de la imagen'),
        ),
        migrations.AddField(
            model_name='plants',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Categorías asociadas a la planta (interior, suculenta, árbol, etc.).', related_name='plants', to='arduino.plantcategory', verbose_name='Categorías'),
        ),
    ]
