# Generated by Django 5.2.8 on 2025-11-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arduino", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sensorzone",
            name="humidity_sensor_pin",
        ),
        migrations.RemoveField(
            model_name="sensorzone",
            name="servo_pin",
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="humidity_max",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="humidity_min",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
