# Generated by Django 5.2.8 on 2025-11-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arduino", "0002_remove_sensorzone_humidity_sensor_pin_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="irrigationevent",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="irrigationevent",
            name="humidity_at_event",
            field=models.FloatField(
                help_text="Humedad (%) al momento del evento de riego."
            ),
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="humidity_max",
            field=models.FloatField(
                blank=True,
                help_text="Humedad máxima (%) a partir de la cual se apaga el riego.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="humidity_min",
            field=models.FloatField(
                blank=True,
                help_text="Humedad mínima (%) antes de encender el riego.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Si está desactivada, el backend no ordenará riego para esta zona.",
            ),
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="last_servo_state",
            field=models.CharField(
                choices=[("ON", "Encendido"), ("OFF", "Apagado")],
                default="OFF",
                help_text="Último estado decidido por el backend para el servomotor.",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="sensorzone",
            name="name",
            field=models.CharField(
                choices=[("Z1", "Zona 1")],
                default="Z1",
                help_text="Identificador de la zona de riego. En este proyecto sólo usamos Z1.",
                max_length=2,
                unique=True,
            ),
        ),
    ]
