# Generated by Django 5.2.8 on 2025-11-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arduino', '0002_plantcategory_plants_image_url_plants_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantcategory',
            name='location',
            field=models.CharField(choices=[('INDOOR', 'Interior'), ('OUTDOOR', 'Exterior'), ('BOTH', 'Ambas')], default='BOTH', help_text='Indica si la planta de esta categoría suele ser de interior, exterior o ambas.', max_length=10, verbose_name='Ubicación'),
        ),
    ]
